### PR TITLE
#58 depandabot added

### PR DESCRIPTION
**Pull request by k-deepak04**
## Related Issue

Closes: #58 

## Checklist:

- [ ] My code adheres to the established style guidelines of this project.
- [ ] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [ ] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
| Original screenshot | Updated screenshot |

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by k-deepak04** [comment]
@swarnavopramanik 
Please add the required labels on all the pull requests so that the Pull Requests that are merged are considered for GSSOC'23 contributions.

**Comment by k-deepak04** [comment]
@swarnavopramanik pleasee add the labels 
as this is not listed in the leader board pr counts

**Comment by swarnavopramanik** [comment]
Yeah I will add

**Comment by k-deepak04** [comment]
> Yeah I will add

yes please add it as soon as possible

**Comment by k-deepak04** [comment]
@swarnavopramanik bro please remove these labels as i have added the bots in other repo also
so it will be counted in spam
Happy to contribute , will look for some other issues
just remove the labels thanks :)

**Comment by swarnavopramanik** [comment]
> @swarnavopramanik bro please remove these labels as i have added the bots in other repo also
> so it will be counted in spam
> Happy to contribute , will look for some other issues
> just remove the labels thanks :)

Okk

**Pull request merged**
