### PR TITLE
#59 Bot added

### PR DESCRIPTION
**Pull request by k-deepak04**
## Related Issue

Closes: #59 

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
| Original screenshot | Updated screenshot |

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by k-deepak04** [comment]
@swarnavopramanik Please add the required labels on all the pull requests so that the Pull Requests that are merged are considered for GSSOC'23 contributions.

**Comment by k-deepak04** [comment]
@swarnavopramanik please add the required label of gssoc'23 and level one as it is not counted
please do this as soon as possible

**Comment by k-deepak04** [comment]
@swarnavopramanik bro please remove these labels as i have added the bots in other repo also
so it will be counted in spam
Happy to contribute , will look for some other issues
just remove the labels thanks :)

**Comment by swarnavopramanik** [comment]
> @swarnavopramanik bro please remove these labels as i have added the bots in other repo also
> so it will be counted in spam
> Happy to contribute , will look for some other issues
> just remove the labels thanks :)

Okk okkk don't worry I will remove

**Pull request merged**
