### PR TITLE
login signup created

### PR DESCRIPTION
**Pull request by vivxsdb**
## Related Issue

Closes: #[issue number]

## Checklist

- [x] My code adheres to the established style guidelines of this project.
- [ ] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [ ] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
| Original screenshot | Updated screenshot |

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by vivxsdb** [comment]
Add please add label to it after merging

**Comment by arnab2001** [comment]
@swarnavopramanik please look into it

**Comment by arnab2001** [comment]
@vivxsdb  can you look into resolving the merge conflict once ? I will review the code and let you know

**Comment by swarnavopramanik** [comment]
@arnab2001 dada this is big change can you look into this

**Comment by vivxsdb** [comment]
How to resolve the merge conflict ? Should I need make a new pull request again

**Pull request closed without merging**
